"use client";
import { queryClient } from "@/lib/client";
import { QueryClientProvider } from "@tanstack/react-query";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        {/* <SideBar/> */}
        <QueryClientProvider 
        client={queryClient} 
        
        >
          {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
